# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for print2pdf package
  - package-ecosystem: "gomod"
    directory: "/print2pdf"
    schedule:
      interval: "weekly"
    groups:
      aws:
        patterns: ['github.com/aws/*']
      chromedp:
        patterns: ['github.com/chromedp/*']
  # Maintain self-dependencies for plain module
  - package-ecosystem: "gomod"
    directory: "/plain"
    schedule:
      interval: "weekly"
    groups:
      chialab:
        patterns: ['github.com/chialab/*']
  # Maintain self-dependencies for lambda module
  - package-ecosystem: "gomod"
    directory: "/lambda"
    schedule:
      interval: "weekly"
    groups:
      aws:
        patterns: ['github.com/aws/*']
      chialab:
        patterns: ['github.com/chialab/*']

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gh-actions:
        patterns: ['actions/*']
      docker:
        patterns: ['docker/*']
      go-lint:
        patterns: ['golangci/*']
      release:
        patterns: ['softprops/*']
