# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for go modules
  - package-ecosystem: "gomod"
    directories:
      - "/print2pdf"
      - "/plain"
      - "/lambda"
    schedule:
      interval: "weekly"
    groups:
      aws:
        patterns: ['github.com/aws/*']
      chialab:
        patterns: ['github.com/chialab/*']
      chromedp:
        patterns: ['github.com/chromedp/*']

  # Maintain dependencies for Terraform module
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
    groups:
      aws:
        patterns: ['aws']

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gh-actions:
        patterns: ['actions/*']
      docker:
        patterns: ['docker/*']
      go-lint:
        patterns: ['golangci/*']
      release:
        patterns: ['softprops/*']
