name: Release binaries

on:
  push:
    tags: [ v* ]

permissions:
  contents: write

jobs:
  release-binaries:
    name: Build and release binaries
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        module: ['plain', 'lambda']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: ${{ matrix.module }}/go.sum
          go-version-file: ${{ matrix.module }}/go.mod

      - name: Build
        env:
          CGO_ENABLED: 0
        run: |
          GOOS=linux GOARCH=amd64 go build -ldflags '-s' -o build/print2pdf-${{ matrix.module }}-linux-amd64 ${{ matrix.module }}
          GOOS=linux GOARCH=arm64 go build -ldflags '-s' -o build/print2pdf-${{ matrix.module }}-linux-arm64 ${{ matrix.module }}
          GOOS=darwin GOARCH=amd64 go build -ldflags '-s' -o build/print2pdf-${{ matrix.module }}-darwin-amd64 ${{ matrix.module }}
          GOOS=darwin GOARCH=arm64 go build -ldflags '-s' -o build/print2pdf-${{ matrix.module }}-darwin-arm64 ${{ matrix.module }}
          GOOS=windows GOARCH=amd64 go build -ldflags '-s' -o build/print2pdf-${{ matrix.module }}-windows-amd64 ${{ matrix.module }}
          GOOS=windows GOARCH=arm64 go build -ldflags '-s' -o build/print2pdf-${{ matrix.module }}-windows-arm64 ${{ matrix.module }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          files: |
            build/print2pdf-${{ matrix.module }}-linux-amd64
            build/print2pdf-${{ matrix.module }}-linux-arm64
            build/print2pdf-${{ matrix.module }}-darwin-amd64
            build/print2pdf-${{ matrix.module }}-darwin-arm64
            build/print2pdf-${{ matrix.module }}-windows-amd64
            build/print2pdf-${{ matrix.module }}-windows-arm64